eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

server:
  port: 8061

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booklink
    username: root
    password: root
    
  application:
    name: book-service
    
  kafka:
    consumer:
      client-id: book-service
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: pe.com.booklink.*
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: tx-book-service        