eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

server:
  port: 9051

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booklink
    username: root
    password: root

  application:
    name: registration-book-service
    
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: tx-registration-book-service
        
  